config/routes.rb
Rails.application.routes.draw do

  root 'home#home'
  get "signup" => "home#signup"
  post 'signup' => 'm_users#create'
  get    'login'   => 'home#login'
  post   'login'   => 'logins#create'
  delete 'logout'  => 'logins#destroy'
  get 'activelistings' => 'listings#active'
  get 'selleritems' => 'listings#seller'
  get 'buyeritems' => 'listings#buyer'
  get 'loggedin' => 'logins#authexpried'
  resources :listings
  resources :m_users
  resources :cart
  delete 'cart' => 'cart#destroy'
  put 'cart' => 'cart#update'
  get 'profile' => 'home#profile'
  get 'home/cart' => 'home#cart'
  get 'new_item' => 'home#new_item'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nwen304Team12</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Nwen 304 Team 12 Marketplace", root_path, class: "navbar-brand" %>
      <div class="js-logged-in-links hide">
        <%= link_to 'New Item', new_item_path, class: "btn btn-primary" %>
        <%= link_to 'Cart', '/home/cart', class: "btn btn-primary" %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <div class="js-logged-in-links hide">
          <li class="alert alert-info js-welcome-user"></li>
          <%= link_to "Profile", '/profile', class: "btn btn-primary" %>
          <button type="button" class="btn btn-primary js-button-logout">Logout</button>
        </div>

        <div class="js-logged-out-links">
          <%= link_to "Sign up now!", '/signup', class: "btn btn-primary" %>
          <%= link_to "Login", '/login', class: "btn btn-primary" %>
        </div>


      </ul>
    </div>
  </div>
</nav>

<%= yield %>

<%= debug(params) if Rails.env.development? %>

<script>
  $(function(){
    onPageLoad();
  });
  $(".js-button-logout").on('click', function () {
    d = {auth_token:getCookie('auth'), user_id:getCookie('id')}
    $.ajax({
      type: "DELETE",
      url: "/logout",
      data: d,
      dataType: "json",
      success: function (responseData, textStatus, jqXHR) {
        setCookie('auth', '', 200);
        setCookie('id', '', 200);
        window.location = '/'
      },
      error: function (jqXHR, textStatus, errorThrown) {
        console.log(errorThrown);
      }
    })
  });
</script>

</body>
</html>